"""make password_hash nullable

Revision ID: 21ea00d3f083
Revises: 6b93267226cf
Create Date: 2026-08-14 12:12:45.625829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21ea00d3f083'
down_revision: Union[str, Sequence[str], None] = '6b93267226cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
