"""add external job ingestion tables

Revision ID: 81cad4f56b50
Revises: 87572d243542
Create Date: 2026-08-19 04:11:15.443553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '81cad4f56b50'
down_revision: Union[str, Sequence[str], None] = '87572d243542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('careers_url', sa.Text(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('connector_key', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=30), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_company_name'), 'job_sources', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_sources_connector_type'), 'job_sources', ['connector_type'], unique=False)
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_table('external_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('workplace_type', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_job_id', name='uq_external_job_source_external_id')
    )
    op.create_index('ix_external_jobs_active_company', 'external_jobs', ['is_active', 'company_name'], unique=False)
    op.create_index(op.f('ix_external_jobs_company_name'), 'external_jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_external_jobs_country'), 'external_jobs', ['country'], unique=False)
    op.create_index(op.f('ix_external_jobs_id'), 'external_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_external_jobs_is_active'), 'external_jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_external_jobs_location'), 'external_jobs', ['location'], unique=False)
    op.create_index(op.f('ix_external_jobs_posted_at'), 'external_jobs', ['posted_at'], unique=False)
    op.create_index(op.f('ix_external_jobs_source_id'), 'external_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_external_jobs_title'), 'external_jobs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_jobs_title'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_source_id'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_posted_at'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_location'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_is_active'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_id'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_country'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_company_name'), table_name='external_jobs')
    op.drop_index('ix_external_jobs_active_company', table_name='external_jobs')
    op.drop_table('external_jobs')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_connector_type'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_company_name'), table_name='job_sources')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
