"""add sample data management

Revision ID: 87572d243542
Revises: 3d381c0269cb
Create Date: 2026-08-17 04:41:52.755706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '87572d243542'
down_revision: Union[str, Sequence[str], None] = '3d381c0269cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_data_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_cleanup_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sample_data_batches_created_at', 'sample_data_batches', ['created_at'], unique=False)
    op.create_index('ix_sample_data_batches_status', 'sample_data_batches', ['status'], unique=False)
    op.create_table('sample_data_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['sample_data_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'object_key', name='uq_sample_data_object_key')
    )
    op.create_index('ix_sample_data_objects_batch_id', 'sample_data_objects', ['batch_id'], unique=False)
    op.create_table('sample_data_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('logical_key', sa.String(length=150), nullable=False),
    sa.Column('pk_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['sample_data_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'table_name', 'logical_key', name='uq_sample_data_record_key')
    )
    op.create_index('ix_sample_data_records_batch_id', 'sample_data_records', ['batch_id'], unique=False)
    op.create_index('ix_sample_data_records_table_name', 'sample_data_records', ['table_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sample_data_records_table_name', table_name='sample_data_records')
    op.drop_index('ix_sample_data_records_batch_id', table_name='sample_data_records')
    op.drop_table('sample_data_records')
    op.drop_index('ix_sample_data_objects_batch_id', table_name='sample_data_objects')
    op.drop_table('sample_data_objects')
    op.drop_index('ix_sample_data_batches_status', table_name='sample_data_batches')
    op.drop_index('ix_sample_data_batches_created_at', table_name='sample_data_batches')
    op.drop_table('sample_data_batches')
    # ### end Alembic commands ###
